Presto_Elasticsearch_Connector_Tutorial
prestodb/prestorials pull request #11
Opened 2023-07-10 00:42 UTC by mahi-cloud99

2023-07-10 17:47 UTC, tdcmeehan requested changes

2023-07-12 15:18 UTC, tdcmeehan commented
Where is the ES connector configured in this documentation?

2023-07-30 23:55 UTC, tdcmeehan commented
Is this still being worked on?

2023-07-31 01:57 UTC, wanglinsong commented
> Where is the ES connector configured in this documentation?

This is more like an ES deployment guide.

2023-07-31 15:07 UTC, closed without merging